### PR TITLE
DockerfileM1

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding Dockerfile which works on M1.

cc @sbesson

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Makes sense to me although this partly brings up some of the question listed in https://github.com/IDR/aspera-client-docker/pull/5
- is the plan to support Docker images for both architectures (x86_64 and arm64)?
- If so which base image should be used? Should this be upgraded to e.g. ubuntu 22.04 or rocky 9?

/cc @jburel

**Review by sbesson — CHANGES_REQUESTED** [review]
Thinking more about it, could you simply add `--platform=linux/amd64` to the FROM line on the main Dockerfile? I suspect this is the most innocuous  change allowing the image to be built in different environments

**Comment by pwalczysko** [comment]
> Thinking more about it, could you simply add `--platform=linux/amd64` to the FROM line on the main Dockerfile? I suspect this is the most innocuous change allowing the image to be built in different environments

Yes, this works on M1, 

```
docker run -ti --rm -v /Users/pwalczysko:/data test-sebm-clever-idea idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/home/data/.aspera/connect/bin/ascp -P33001 -l 40m -i /home/data/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 0 fasp-public@fasp.ebi.ac.uk:/pub/databases/IDR/idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A
001005001.flex                                                     58%   51MB 38.9Mb/s    00:08 ETA
```

**Comment by pwalczysko** [comment]
I have also verified on my old mac that the Dockerfile now works for both M1 and Intel Mac OS X.
I will remove the DockerM1 file.

**Comment by pwalczysko** [comment]
> * is the plan to support Docker images for both architectures (x86_64 and arm64)?

I would say definitely - with https://github.com/sbesson/aspera-client-docker/pull/1/commits/9cc1c02dcad5fa9dbbd9dcf0132b2c673105ac5b this is simple to achieve. If we do not support M1, we will loose the ability to easily debug user reports about docker-based aspera workflows as we use M1 ourselves :)

**Comment by pwalczysko** [comment]
> * If so which base image should be used? Should this be upgraded to e.g. ubuntu 22.04 or rocky 9?

Tried briefly ubuntu 22.04 - big permission problems. The user cited in the Dockerfile is not able to install the required software inside the docker - not sure how to adjust that.

**Review by sbesson — APPROVED** [review]

**Pull request merged**
